import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdtemp,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {coverageFor,validateCatalog,generateCatalog,publishCatalog,buildMonthly} from '../scripts/catalog.mjs';
const october=JSON.parse(await readFile('content/monthly/2026-10.json','utf8'));
const copy=()=>structuredClone(october);
function november(){const c=copy();c.catalogId='2026-11';c.coverage=coverageFor(c.catalogId);c.provenance={producer:'chatgpt-work',notes:'Synthetic test, not a researched publication'};c.events=[{...c.events[0],origin:'chatgpt-work',sessions:[{start:'2026-11-01T10:00',end:null},{start:'2026-11-30T10:00',end:'2026-11-30T12:00'}]}];return c;}
test('October 10–31 and calendar-variable months including leap year',()=>{validateCatalog(october);assert.deepEqual(october.coverage,{start:'2026-10-10',end:'2026-10-31'});validateCatalog(november());assert.deepEqual(coverageFor('2026-11'),{start:'2026-11-01',end:'2026-11-30'});assert.equal(coverageFor('2026-12').end,'2026-12-31');assert.equal(coverageFor('2027-01').end,'2027-01-31');assert.equal(coverageFor('2028-02').end,'2028-02-29');});
test('schema rejects missing fields, bad ranges, extras, mismatched filename and duplicate stable IDs',()=>{for(const mutate of [c=>delete c.events[0].city,c=>c.events[0].points.children=31,c=>c.events[0].points.comfort=-1,c=>c.events[0].points.distance=1.5,c=>c.events[0].points.cost=10,c=>c.events.push(c.events[0]),c=>c.events[0].familyPrice=-1,c=>c.events[0].source='javascript:alert(1)',c=>c.coverage.start='2026-10-01',c=>c.events[0].sessions[0].start='2026-10-09T10:00',c=>c.events[0].sessions[0].start='2026-10-32T10:00',c=>c.events[0].verifiedAt='not-a-date']){const c=copy();mutate(c);assert.throws(()=>validateCatalog(c));}assert.throws(()=>validateCatalog(october,'2026-11.json'));});
test('generation preserves IDs and deterministic price-independent rating',()=>{const first=generateCatalog(october);assert.deepEqual(first.events.map(e=>e.id),october.events.map(e=>e.id));for(const familyPrice of [null,0,999]){const c=copy();c.events[0].familyPrice=familyPrice;assert.equal(generateCatalog(c).events[0].rating,85);}const c=copy();c.events[0].points={children:30,comfort:20,distance:15,uniqueness:10};assert.equal(generateCatalog(c).events[0].rating,100);});
test('DST gaps rejected, November fall-back and unknown end supported',()=>{const c=november();c.catalogId='2027-03';c.coverage=coverageFor(c.catalogId);c.events[0].sessions=[{start:'2027-03-14T02:30',end:null}];assert.throws(()=>validateCatalog(c));c.events[0].sessions=[{start:'2027-03-14T03:30',end:null}];validateCatalog(c);validateCatalog(november());});
test('invalid publication preserves the exact existing output',async()=>{const dir=await mkdtemp(join(tmpdir(),'family-events-'));try{const output=join(dir,'events.json');await publishCatalog(october,output);const valid=await readFile(output,'utf8');const invalid=copy();invalid.events[0].points.children=100;await assert.rejects(publishCatalog(invalid,output));assert.equal(await readFile(output,'utf8'),valid);}finally{await rm(dir,{recursive:true,force:true});}});
test('staged November activates only at New York midnight and invalid future input cannot overwrite output',async()=>{const dir=await mkdtemp(join(tmpdir(),'family-months-'));try{await writeFile(join(dir,'2026-10.json'),JSON.stringify(october));await writeFile(join(dir,'2026-11.json'),JSON.stringify(november()));const output=join(dir,'published.txt');assert.equal((await buildMonthly(dir,output,new Date('2026-11-01T03:59:00Z'))).catalogId,'2026-10');assert.equal((await buildMonthly(dir,output,new Date('2026-11-01T04:00:00Z'))).catalogId,'2026-11');const previous=await readFile(output,'utf8');await writeFile(join(dir,'2026-12.json'),'{}');await assert.rejects(buildMonthly(dir,output,new Date('2026-11-01T04:00:00Z')));assert.equal(await readFile(output,'utf8'),previous);}finally{await rm(dir,{recursive:true,force:true});}});
