import {test,expect} from '@playwright/test';
import fs from 'node:fs/promises';
const catalog=JSON.parse(await fs.readFile('public/data/events.json','utf8'));
test.beforeEach(async({page})=>{await page.route('**/data/events.json',route=>route.fulfill({json:catalog}));await page.clock.setFixedTime(new Date('2026-10-09T12:00:00Z'));await page.goto('/');await expect(page.locator('.card')).toHaveCount(2);});
test('mobile catalogue, categories, details, calendar and persistent selections',async({page})=>{expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.locator('#category').selectOption('farm');await expect(page.locator('.card')).toHaveCount(1);await page.locator('.card summary').click();await expect(page.getByLabel('Дата події')).toBeVisible();await page.getByLabel('Дата події').selectOption('2026-10-10T10:00');const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'↓ Apple Calendar',exact:true}).click();const download=await downloadPromise;expect(download.suggestedFilename()).toContain('2026-10-10.ics');const file=await fs.readFile(await download.path(),'utf8');expect(file).toContain('DTSTART;TZID=America/New_York:20261010T100000');await page.getByRole('button',{name:/Додано/}).click();await expect(page.locator('.card.added')).toHaveCount(1);await page.reload();await expect(page.locator('.card')).toHaveCount(1);await page.getByRole('button',{name:/Додано/}).click();await expect(page.locator('.card.added')).toHaveCount(1);await page.locator('.card summary').click();await page.getByRole('button',{name:'↩ Повернути до «Усі»'}).click();await page.getByRole('button',{name:/^Усі/}).click();await expect(page.locator('.card')).toHaveCount(2);});
test('rejection requires confirmation and can be restored; single day has no date selector',async({page})=>{await page.locator('.card').first().locator('summary').click();await expect(page.getByLabel('Дата події')).toHaveCount(1);await expect(page.getByLabel('Дата події')).not.toBeVisible();await page.getByRole('button',{name:'Відхилити',exact:true}).first().click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Залишити'}).click();await expect(page.locator('.card')).toHaveCount(2);await page.getByRole('button',{name:'Відхилити',exact:true}).first().click();await page.getByRole('dialog').getByRole('button',{name:'Відхилити'}).click();await expect(page.locator('.card')).toHaveCount(1);await page.getByRole('button',{name:/Відхилено/}).click();await expect(page.locator('.card.rejected')).toHaveCount(1);await page.locator('.card summary').click();await page.getByRole('button',{name:'↩ Повернути до «Усі»'}).click();await page.getByRole('button',{name:/^Усі/}).click();await expect(page.locator('.card')).toHaveCount(2);});
test('publishing a new month resets state; same-month refresh preserves state',async({page})=>{await page.evaluate(period=>localStorage.setItem('family-events:v1',JSON.stringify({period,selections:{'great-pumpkin-fest-2026':{status:'added'}}})),catalog.catalogId);await page.reload();await expect(page.locator('.card')).toHaveCount(1);await page.route('**/data/events.json',route=>route.fulfill({json:{...catalog,catalogId:'2026-11'}}));await page.reload();await expect(page.locator('.card')).toHaveCount(2);});
test('catalogue fetch errors show useful feedback',async({page})=>{await page.route('**/data/events.json',r=>r.fulfill({status:503}));await page.reload();await expect(page.getByText('Каталог тимчасово недоступний')).toBeVisible();});

test('Escape never confirms a rejection after a previous confirmed dialog',async({page})=>{await page.locator('.card').first().locator('summary').click();await page.getByRole('button',{name:'Відхилити',exact:true}).first().click();await page.getByRole('dialog').getByRole('button',{name:'Відхилити'}).click();await expect(page.locator('.card')).toHaveCount(1);await page.locator('.card summary').click();await page.getByRole('button',{name:'Відхилити',exact:true}).first().click();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible();await expect(page.locator('.card')).toHaveCount(1);});

test('light and dark theme follow system initially, persist preference and preserve selections',async({page})=>{await page.emulateMedia({colorScheme:'dark'});await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await expect(page.locator('html')).toHaveCSS('background-color','rgb(10, 10, 10)');await page.getByRole('button',{name:'Увімкнути світлу тему'}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','light');await expect(page.locator('html')).toHaveCSS('background-color','rgb(255, 255, 255)');await page.reload();await expect(page.locator('html')).toHaveAttribute('data-theme','light');await page.getByRole('button',{name:'Увімкнути темну тему'}).click();await page.locator('.card').first().locator('summary').click();await page.getByRole('button',{name:'↓ Apple Calendar',exact:true}).first().click();await page.getByRole('button',{name:/Додано/}).click();await expect(page.locator('.card.added')).toHaveCSS('background-color','rgb(16, 44, 27)');await page.getByRole('button',{name:'Увімкнути світлу тему'}).click();await expect(page.locator('.card.added')).toHaveCount(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();});
test('past sessions disappear from main catalog without waiting for monthly refresh',async({page})=>{await page.clock.setFixedTime(new Date('2026-10-12T12:00:00Z'));await page.reload();await expect(page.locator('.card')).toHaveCount(1);await page.locator('.card summary').click();await expect(page.getByLabel('Дата події')).not.toContainText('9 жовт.');});
