import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {calendar,rating,readState,saveState,visibleEvents,monthId,upcomingEvents,validateEvent,foldLine} from '../src/core.js';import {refresh,verify,sourceText} from '../scripts/refresh.mjs';
const config=JSON.parse(await readFile('config/sources.json','utf8')),e=config.events[0],farm=config.events[1];
test('ratings follow all five weighted limits',()=>{assert.equal(rating(e),89);config.events.forEach(validateEvent);assert.throws(()=>validateEvent({...e,points:{...e.points,children:31}}));});
test('month boundary uses New York in summer and winter',()=>{assert.equal(monthId(new Date('2026-10-01T03:59:00Z')),'2026-09');assert.equal(monthId(new Date('2026-10-01T04:00:00Z')),'2026-10');assert.equal(monthId(new Date('2026-12-01T04:59:00Z')),'2026-11');assert.equal(monthId(new Date('2026-12-01T05:00:00Z')),'2026-12');});
test('selection persists only for the published month, corrupted or unavailable storage is safe',()=>{let value;const storage={getItem:()=>value,setItem:(k,v)=>value=v};const s={period:'2026-10',selections:{a:{status:'added'}}};assert.ok(saveState(storage,s));assert.deepEqual(readState(storage,s.period),s);assert.deepEqual(readState(storage,'2026-11').selections,{});value='{';assert.deepEqual(readState(storage,s.period).selections,{});assert.equal(saveState({setItem:()=>{throw Error();}},s),false);});
test('tab/category filters and sorts work',()=>{assert.deepEqual(visibleEvents(config.events,{},'all','farm','rating'),[farm]);assert.deepEqual(visibleEvents(config.events,{[e.id]:{status:'rejected'}},'rejected','all','date'),[e]);assert.equal(visibleEvents(config.events,{},'all','all','price')[0].id,e.id);assert.equal(visibleEvents(config.events,{},'all','all','rating')[0].id,e.id);});
test('calendar is RFC5545 with TZID, DST, escaped content and UTF-8 folding',()=>{const result=calendar({...e,name:'А'.repeat(60)+',;\n'},e.sessions[0],new Date('2026-10-09T12:00:00Z'));assert.match(result,/DTSTART;TZID=America\/New_York:20261010T100000/);assert.match(result,/DTEND;TZID=America\/New_York:20261010T150000/);assert.match(result,/DTSTAMP:20261009T120000Z/);assert.match(result,/BEGIN:VTIMEZONE/);assert.match(result,/TZOFFSETTO:-0500/);assert.ok(result.endsWith('END:VCALENDAR\r\n'));for(const line of result.split('\r\n'))assert.ok(Buffer.byteLength(line)<=75);assert.ok(result.replace(/\r\n /g,'').includes('\\,\\;\\n'));assert.throws(()=>calendar(e,farm.sessions[0]));assert.ok(foldLine('А'.repeat(60)).includes('\r\n '));});
test('HTML text extraction ignores scripts, normalizes whitespace and decodes entities',()=>assert.equal(sourceText('<body><script>canceled</script><p>A&nbsp; B &amp; C</p></body>'),'A B & C'));
test('changed prices, missing evidence and cancellation notices fail closed',()=>{verify('General Admission: $15',['General Admission: $15']);assert.throws(()=>verify('General Admission: $20',['General Admission: $15']));assert.throws(()=>verify('event postponed',['event']));});
test('refresh verifies configured real source shapes and expires sessions',async()=>{const mocked=async url=>({ok:true,text:async()=>'<body>'+config.events.flatMap(e=>e.checks.filter(c=>c.url===url).flatMap(c=>c.evidence)).join(' ')+'</body>'});const result=await refresh(config,new Date('2026-10-09T12:00:00Z'),mocked);assert.equal(result.events.length,2);assert.equal(result.catalogId,'2026-10');assert.equal(result.discoveryEnabled,false);const next=await refresh(config,new Date('2026-10-12T12:00:00Z'),mocked);assert.equal(next.events.length,1);assert.equal(next.events[0].sessions[0].start,'2026-10-16T17:00');assert.equal((await refresh(config,new Date('2026-11-02T12:00:00Z'),mocked)).events.length,0);});
test('unreachable or changed sources are quarantined, never fabricated',async()=>{const result=await refresh(config,new Date('2026-10-09T12:00:00Z'),async()=>({ok:false,status:403}));assert.equal(result.events.length,0);assert.equal(result.issues.length,2);});

test('legacy weekly selections migrate within the same month',()=>{assert.deepEqual(readState({getItem:()=>JSON.stringify({week:'2026-10-05',selections:{a:{status:'added'}}})},'2026-10'),{period:'2026-10',selections:{a:{status:'added'}}});});
test('monthly refresh excludes next-month sessions and browser hides expired sessions',async()=>{const mock=async url=>({ok:true,text:async()=>'<body>'+config.events.flatMap(e=>e.checks.filter(c=>c.url===url).flatMap(c=>c.evidence)).join(' ')+'</body>'});const oct=await refresh(config,new Date('2026-10-01T12:00:00Z'),mock);assert.ok(oct.events.flatMap(e=>e.sessions).every(s=>s.start.startsWith('2026-10')));const nov=await refresh(config,new Date('2026-11-01T12:00:00Z'),mock);assert.equal(nov.catalogId,'2026-11');assert.equal(nov.events[0].sessions.length,1);assert.equal(upcomingEvents([e],new Date('2026-10-10T19:00:00Z')).length,0);});
