import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {calendar,rating,readState,saveState,visibleEvents,monthId,upcomingEvents,validateEvent,foldLine} from '../src/core.js';import {refresh,verify,sourceText} from '../scripts/refresh.mjs';
const fullConfig=JSON.parse(await readFile('config/sources.json','utf8'));const config={...fullConfig,events:fullConfig.events.slice(0,2)},e=config.events[0],farm=config.events[1];
test('ratings normalize four components and ignore every price',()=>{assert.equal(rating(e),85);for(const familyPrice of [null,0,20,100,1000])assert.equal(rating({...e,familyPrice,points:{...e.points,cost:familyPrice===null?0:25}}),85);assert.equal(rating({...e,points:{children:30,comfort:20,distance:15,uniqueness:10}}),100);assert.equal(rating({...e,points:{children:0,comfort:0,distance:0,uniqueness:0}}),0);config.events.forEach(validateEvent);assert.throws(()=>validateEvent({...e,points:{...e.points,children:31}}));});
test('month boundary uses New York in summer and winter',()=>{assert.equal(monthId(new Date('2026-10-01T03:59:00Z')),'2026-09');assert.equal(monthId(new Date('2026-10-01T04:00:00Z')),'2026-10');assert.equal(monthId(new Date('2026-12-01T04:59:00Z')),'2026-11');assert.equal(monthId(new Date('2026-12-01T05:00:00Z')),'2026-12');});
test('selection persists only for the published month, corrupted or unavailable storage is safe',()=>{let value;const storage={getItem:()=>value,setItem:(k,v)=>value=v};const s={period:'2026-10',selections:{a:{status:'added'}}};assert.ok(saveState(storage,s));assert.deepEqual(readState(storage,s.period),s);assert.deepEqual(readState(storage,'2026-11').selections,{});value='{';assert.deepEqual(readState(storage,s.period).selections,{});assert.equal(saveState({setItem:()=>{throw Error();}},s),false);});
test('tab/category filters and sorts work',()=>{assert.deepEqual(visibleEvents(config.events,{},'all','farm','rating'),[farm]);assert.deepEqual(visibleEvents(config.events,{[e.id]:{status:'rejected'}},'rejected','all','date'),[e]);assert.equal(visibleEvents(config.events,{},'all','all','price')[0].id,e.id);assert.equal(visibleEvents(config.events,{},'all','all','rating')[0].id,e.id);});
test('calendar is RFC5545 with TZID, DST, escaped content and UTF-8 folding',()=>{const result=calendar({...e,name:'А'.repeat(60)+',;\n'},e.sessions[0],new Date('2026-10-09T12:00:00Z'));assert.match(result,/DTSTART;TZID=America\/New_York:20261010T100000/);assert.match(result,/DTEND;TZID=America\/New_York:20261010T150000/);assert.match(result,/DTSTAMP:20261009T120000Z/);assert.match(result,/BEGIN:VTIMEZONE/);assert.match(result,/TZOFFSETTO:-0500/);assert.ok(result.endsWith('END:VCALENDAR\r\n'));for(const line of result.split('\r\n'))assert.ok(Buffer.byteLength(line)<=75);assert.ok(result.replace(/\r\n /g,'').includes('\\,\\;\\n'));assert.throws(()=>calendar(e,farm.sessions[0]));assert.ok(foldLine('А'.repeat(60)).includes('\r\n '));});
test('HTML text extraction ignores scripts, normalizes whitespace and decodes entities',()=>assert.equal(sourceText('<body><script>canceled</script><p>A&nbsp; B &amp; C</p></body>'),'A B & C'));
test('changed prices, missing evidence and cancellation notices fail closed',()=>{verify('General Admission: $15',['General Admission: $15']);assert.throws(()=>verify('General Admission: $20',['General Admission: $15']));assert.throws(()=>verify('event postponed',['event']));});
test('refresh verifies configured real source shapes and expires sessions',async()=>{const mocked=async url=>({ok:true,text:async()=>'<body>'+config.events.flatMap(e=>e.checks.filter(c=>c.url===url).flatMap(c=>c.evidence)).join(' ')+'</body>'});const result=await refresh(config,new Date('2026-10-09T12:00:00Z'),mocked);assert.equal(result.events.length,2);assert.equal(result.catalogId,'2026-10');assert.equal(result.discoveryEnabled,false);const next=await refresh(config,new Date('2026-10-12T12:00:00Z'),mocked);assert.equal(next.events.length,1);assert.equal(next.events[0].sessions[0].start,'2026-10-16T17:00');assert.equal((await refresh(config,new Date('2026-11-02T12:00:00Z'),mocked)).events.length,0);});
test('unreachable or changed sources are quarantined, never fabricated',async()=>{const result=await refresh(config,new Date('2026-10-09T12:00:00Z'),async()=>({ok:false,status:403}));assert.equal(result.events.length,0);assert.equal(result.issues.length,2);});

test('legacy weekly selections migrate within the same month',()=>{assert.deepEqual(readState({getItem:()=>JSON.stringify({week:'2026-10-05',selections:{a:{status:'added'}}})},'2026-10'),{period:'2026-10',selections:{a:{status:'added'}}});});
test('monthly refresh excludes next-month sessions and browser hides expired sessions',async()=>{const mock=async url=>({ok:true,text:async()=>'<body>'+config.events.flatMap(e=>e.checks.filter(c=>c.url===url).flatMap(c=>c.evidence)).join(' ')+'</body>'});const oct=await refresh(config,new Date('2026-10-01T12:00:00Z'),mock);assert.ok(oct.events.flatMap(e=>e.sessions).every(s=>s.start.startsWith('2026-10')));const nov=await refresh(config,new Date('2026-11-01T12:00:00Z'),mock);assert.equal(nov.catalogId,'2026-11');assert.equal(nov.events[0].sessions.length,1);assert.equal(upcomingEvents([e],new Date('2026-10-10T19:00:00Z')).length,0);});

test('all expanded records validate and unknown ending stays unknown in ICS',()=>{fullConfig.events.forEach(validateEvent);const service=fullConfig.events.find(e=>e.sessions.some(s=>s.end===null));const text=calendar(service,service.sessions[0]);assert.ok(!text.includes('DTEND;TZID'));assert.match(text,/DTSTART;TZID=America\/New_York:20261011T104500/);});
test('official metadata can provide event description without executing scripts',()=>{assert.equal(sourceText('<head><meta name="description" content="Family event 2026"></head><body>Hours<script>canceled</script></body>',true),'Hours Family event 2026');});

test('source scan collects only configured HTTPS hosts and never publishes candidates',async()=>{
 const {extractCandidates,scanSources}=await import('../scripts/scan-sources.mjs');
 const source={id:'church',name:'Church',url:'https://example.org/events',allowedLinkedHosts:['example.churchcenter.com'],linkPatterns:['/events/']};
 const html='<a href="/events/fall#join">Fall &amp; games</a><a href="/events/fall">Fall &amp; games</a><a href="https://example.churchcenter.com/events/123">Registration</a><a href="https://evil.test/events/123">Untrusted</a><a href="javascript:alert(1)">Bad</a><a href="http://example.org/events/123">HTTP</a>';
 assert.deepEqual(extractCandidates(html,source).map(c=>c.url),['https://example.org/events/fall','https://example.churchcenter.com/events/123']);
 const report=await scanSources({sources:[source],notes:'Review required'},async()=>({ok:true,text:async()=>html}));
 assert.equal(report.autoPublishCandidates,false);assert.equal(report.aiApiConnected,false);assert.equal(report.sources[0].candidates[0].status,'requires-editorial-review');
 const failed=await scanSources({sources:[source]},async()=>({ok:false,status:403}));assert.equal(failed.sources[0].status,'unavailable');assert.deepEqual(failed.sources[0].candidates,[]);
});

test('local farms filter requires provenance and combines with category, tabs and sorting',()=>{
 const park={...farm,id:'park-pumpkins',name:'Pumpkin day in a city park',farm:undefined};
 const festival={...farm,id:'farm-festival',category:'festival'};
 assert.deepEqual(visibleEvents([park,farm,festival],{},'all','all','rating',true),[farm,festival]);
 assert.deepEqual(visibleEvents([park,farm,festival],{},'all','farm','rating',true),[farm]);
 assert.deepEqual(visibleEvents([park,farm],{[farm.id]:{status:'added'}},'added','all','price',true),[farm]);
 assert.deepEqual(visibleEvents([park],{},'all','farm','rating',true),[]);
 assert.throws(()=>validateEvent({...farm,farm:{name:'Unknown',source:'javascript:alert(1)'}}));
});
